baseurl = "https://www.jingwyang.com"
enableEmoji = true
hasCJKlanguage = true
languageCode = "en-us"
title = "My Awesome Site"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    blog = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight= 3
[[menu.main]]
    name = "博客"
    url = "/blog/"
    weight= 2
[[menu.main]]
    name = "关于"
    url = "/about-me/"
    weight= 4
[[menu.main]]
    name = "首页"
    url = "/"
    weight= 1

[params]
    description = "Personal website of JingwYang."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"
    author = "Jingwen Yang"
    dataFormat = "2006/01/02"
    [params.logo]
    url = "logo1.jpeg"
    width = 200
    height = 200
    alt = "Logo"

